### ISSUE TITLE
provide options.ignoreSheets explicitly

### ISSUE THREAD

**Issue by nimo23** [ben-eb/gulp-uncss#36]
Accordding to the docs:

**Note that options.ignoreSheets is already defined for you. gulp-uncss will only process CSS files in the stream.**

There are some cases, where it makes sense to define ignoreSheets again and explicitly. For example, when stream contains css which should not be processed by gulp-uncss but processed my gulp-mincss, both within the pipe.

stream.src(..)
.pipe(mincss)
.pipe(uncss(ignoreSheets(ignoreSheets: regex));

So please provide the **'ignoreSheets' property** within your **gulp-uncss**.

Thanks in advance!

**Comment by ben-eb** [comment]
The ignoreSheets option is to disable UnCSS looking in the HTML file itself for CSS to process. Since the CSS comes from the stream this option usually leads to duplicate CSS processing. https://github.com/ben-eb/gulp-uncss/pull/4

If you need to filter out CSS files in the stream then use https://github.com/sindresorhus/gulp-filter.
