### ISSUE TITLE
with generator-gulp-angular, gulp uncss stripping all styles 

### ISSUE THREAD

**Issue by bennyp123** [ben-eb/gulp-uncss#55]
Hi there,
I'm <del>mashing at the keyb</del> trying to get generator-gulp-angular's cssFilter to use uncss. I've tried adding `.pipe(uncss({html:'src/app/**/*.html'}))` in between `.pipe(cssFilter)` and `.pipe(cssFilter.restore`

When I build, I get a page without any styles at all. in /dist/styles vendor.css is empty (232b) and app.css is only 111 lines unminified. (2kb)

when I comment out the uncss pipe, app.css is 164kb and vendor.css is 63kb

Not really sure what's going on here: if this is an issue with gulp-uncss, the generator, or it's PEBCAK.

**Comment by ben-eb** [comment]
I'm not an Angular user so I don't know the specifics of this issue, but UnCSS only handles JavaScript added *on page load*. So my guess is that it is removing CSS classes that it cannot 'see' because they are handled by Angular.

In this case if you still want to use UnCSS my advice is the same as in this thread - https://github.com/ben-eb/gulp-uncss/issues/52#issuecomment-202168435
